// <auto-generated />
using System;
using BodyByBurgersInfoApi.BusinessLogic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BodyByBurgersInfoApi.Migrations
{
    [DbContext(typeof(InfoContext))]
    [Migration("20240816100021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "leaf",
                            Name = "Lettuce"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "new-box",
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "new-box",
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "cheese",
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "new-box",
                            Name = "Pickles"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "pig-variant-outline",
                            Name = "Bacon"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "new-box",
                            Name = "Ketchup"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "new-box",
                            Name = "Mustard"
                        },
                        new
                        {
                            Id = 9,
                            Icon = "new-box",
                            Name = "Mayonnaise"
                        },
                        new
                        {
                            Id = 10,
                            Icon = "cow",
                            Name = "Beef Patty"
                        },
                        new
                        {
                            Id = 11,
                            Icon = "chicken",
                            Name = "Chicken Patty"
                        },
                        new
                        {
                            Id = 12,
                            Icon = "leaf",
                            Name = "Veggie Patty"
                        },
                        new
                        {
                            Id = 13,
                            Icon = "egg-fried",
                            Name = "Fried Egg"
                        },
                        new
                        {
                            Id = 14,
                            Icon = "cheese",
                            Name = "Cheddar"
                        },
                        new
                        {
                            Id = 15,
                            Icon = "cheese",
                            Name = "Gouda"
                        },
                        new
                        {
                            Id = 16,
                            Icon = "cheese",
                            Name = "American"
                        },
                        new
                        {
                            Id = 17,
                            Icon = "cheese",
                            Name = "Mozzarella"
                        },
                        new
                        {
                            Id = 18,
                            Icon = "cheese",
                            Name = "Swiss"
                        },
                        new
                        {
                            Id = 19,
                            Icon = "cheese",
                            Name = "Pepper Jack"
                        },
                        new
                        {
                            Id = 20,
                            Icon = "bread-slice-outline",
                            Name = "Brioche Bun"
                        },
                        new
                        {
                            Id = 21,
                            Icon = "bread-slice-outline",
                            Name = "Sesame Bun"
                        },
                        new
                        {
                            Id = 22,
                            Icon = "bread-slice-outline",
                            Name = "Pretzel Bun"
                        },
                        new
                        {
                            Id = 23,
                            Icon = "bread-slice-outline",
                            Name = "Ciabatta Bun"
                        },
                        new
                        {
                            Id = 24,
                            Icon = "bread-slice-outline",
                            Name = "Gluten Free Bun"
                        },
                        new
                        {
                            Id = 25,
                            Icon = "bread-slice-outline",
                            Name = "Wheat Bun"
                        },
                        new
                        {
                            Id = 26,
                            Icon = "liquid-spot",
                            Name = "Mayo"
                        },
                        new
                        {
                            Id = 27,
                            Icon = "liquid-spot",
                            Name = "Hot Sauce"
                        },
                        new
                        {
                            Id = 28,
                            Icon = "liquid-spot",
                            Name = "BBQ Sauce"
                        },
                        new
                        {
                            Id = 29,
                            Icon = "liquid-spot",
                            Name = "Ranch"
                        },
                        new
                        {
                            Id = 30,
                            Icon = "liquid-spot",
                            Name = "Buffalo Sauce"
                        },
                        new
                        {
                            Id = 31,
                            Icon = "liquid-spot",
                            Name = "Honey Mustard"
                        },
                        new
                        {
                            Id = 32,
                            Icon = "liquid-spot",
                            Name = "Chipotle Mayo"
                        },
                        new
                        {
                            Id = 33,
                            Icon = "liquid-spot",
                            Name = "Garlic Aioli"
                        },
                        new
                        {
                            Id = 34,
                            Icon = "liquid-spot",
                            Name = "Truffle Aioli"
                        },
                        new
                        {
                            Id = 35,
                            Icon = "peanut-outline",
                            Name = "Peanut Butter"
                        },
                        new
                        {
                            Id = 36,
                            Icon = "jellyfish-outline",
                            Name = "Jelly"
                        },
                        new
                        {
                            Id = 37,
                            Icon = "pig-variant-outline",
                            Name = "Bacon Jam"
                        },
                        new
                        {
                            Id = 38,
                            Icon = "pig-variant-outline",
                            Name = "Pulled Pork"
                        },
                        new
                        {
                            Id = 39,
                            Icon = "new-box",
                            Name = "Onion Rings"
                        },
                        new
                        {
                            Id = 40,
                            Icon = "new-box",
                            Name = "Fried Pickles"
                        },
                        new
                        {
                            Id = 41,
                            Icon = "chili-hot-outline",
                            Name = "Jalapenos"
                        },
                        new
                        {
                            Id = 42,
                            Icon = "new-box",
                            Name = "Avocado"
                        },
                        new
                        {
                            Id = 43,
                            Icon = "new-box",
                            Name = "Mushrooms"
                        },
                        new
                        {
                            Id = 44,
                            Icon = "new-box",
                            Name = "Caramelized Onions"
                        },
                        new
                        {
                            Id = 45,
                            Icon = "cow",
                            Name = "Wagyu Beef"
                        },
                        new
                        {
                            Id = 46,
                            Icon = "star",
                            Name = "Special Sauce"
                        },
                        new
                        {
                            Id = 47,
                            Icon = "cow",
                            Name = "Black Angus"
                        },
                        new
                        {
                            Id = 48,
                            Icon = "liquid-spot",
                            Name = "Stack Sauce"
                        },
                        new
                        {
                            Id = 49,
                            Icon = "new-box",
                            Name = "Fries"
                        },
                        new
                        {
                            Id = 50,
                            Icon = "chili-hot-outline",
                            Name = "Chillies"
                        },
                        new
                        {
                            Id = 51,
                            Icon = "chili-hot-outline",
                            Name = "Fried Jalapenos"
                        },
                        new
                        {
                            Id = 52,
                            Icon = "new-box",
                            Name = "Red Onions"
                        },
                        new
                        {
                            Id = 53,
                            Icon = "cow",
                            Name = "Ground Rib-Eye"
                        });
                });

            modelBuilder.Entity("IngredientReview", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("IngredientsId", "ReviewId");

                    b.HasIndex("ReviewId");

                    b.ToTable("IngredientReview");

                    b.HasData(
                        new
                        {
                            IngredientsId = 14,
                            ReviewId = 1
                        },
                        new
                        {
                            IngredientsId = 4,
                            ReviewId = 1
                        },
                        new
                        {
                            IngredientsId = 6,
                            ReviewId = 1
                        },
                        new
                        {
                            IngredientsId = 14,
                            ReviewId = 2
                        },
                        new
                        {
                            IngredientsId = 16,
                            ReviewId = 3
                        },
                        new
                        {
                            IngredientsId = 2,
                            ReviewId = 3
                        },
                        new
                        {
                            IngredientsId = 44,
                            ReviewId = 3
                        },
                        new
                        {
                            IngredientsId = 5,
                            ReviewId = 3
                        },
                        new
                        {
                            IngredientsId = 21,
                            ReviewId = 3
                        },
                        new
                        {
                            IngredientsId = 10,
                            ReviewId = 5
                        },
                        new
                        {
                            IngredientsId = 16,
                            ReviewId = 5
                        },
                        new
                        {
                            IngredientsId = 41,
                            ReviewId = 5
                        },
                        new
                        {
                            IngredientsId = 50,
                            ReviewId = 5
                        },
                        new
                        {
                            IngredientsId = 46,
                            ReviewId = 5
                        },
                        new
                        {
                            IngredientsId = 20,
                            ReviewId = 5
                        },
                        new
                        {
                            IngredientsId = 10,
                            ReviewId = 10
                        },
                        new
                        {
                            IngredientsId = 16,
                            ReviewId = 10
                        },
                        new
                        {
                            IngredientsId = 7,
                            ReviewId = 10
                        },
                        new
                        {
                            IngredientsId = 3,
                            ReviewId = 10
                        },
                        new
                        {
                            IngredientsId = 10,
                            ReviewId = 11
                        },
                        new
                        {
                            IngredientsId = 16,
                            ReviewId = 11
                        },
                        new
                        {
                            IngredientsId = 48,
                            ReviewId = 11
                        },
                        new
                        {
                            IngredientsId = 9,
                            ReviewId = 11
                        },
                        new
                        {
                            IngredientsId = 44,
                            ReviewId = 11
                        },
                        new
                        {
                            IngredientsId = 10,
                            ReviewId = 12
                        },
                        new
                        {
                            IngredientsId = 16,
                            ReviewId = 12
                        },
                        new
                        {
                            IngredientsId = 3,
                            ReviewId = 12
                        },
                        new
                        {
                            IngredientsId = 5,
                            ReviewId = 12
                        },
                        new
                        {
                            IngredientsId = 8,
                            ReviewId = 12
                        },
                        new
                        {
                            IngredientsId = 26,
                            ReviewId = 12
                        },
                        new
                        {
                            IngredientsId = 10,
                            ReviewId = 13
                        },
                        new
                        {
                            IngredientsId = 14,
                            ReviewId = 13
                        },
                        new
                        {
                            IngredientsId = 6,
                            ReviewId = 13
                        },
                        new
                        {
                            IngredientsId = 27,
                            ReviewId = 13
                        },
                        new
                        {
                            IngredientsId = 49,
                            ReviewId = 13
                        },
                        new
                        {
                            IngredientsId = 1,
                            ReviewId = 13
                        },
                        new
                        {
                            IngredientsId = 41,
                            ReviewId = 13
                        },
                        new
                        {
                            IngredientsId = 16,
                            ReviewId = 14
                        },
                        new
                        {
                            IngredientsId = 6,
                            ReviewId = 14
                        },
                        new
                        {
                            IngredientsId = 43,
                            ReviewId = 14
                        },
                        new
                        {
                            IngredientsId = 3,
                            ReviewId = 14
                        },
                        new
                        {
                            IngredientsId = 41,
                            ReviewId = 14
                        },
                        new
                        {
                            IngredientsId = 51,
                            ReviewId = 15
                        },
                        new
                        {
                            IngredientsId = 19,
                            ReviewId = 15
                        },
                        new
                        {
                            IngredientsId = 9,
                            ReviewId = 15
                        },
                        new
                        {
                            IngredientsId = 3,
                            ReviewId = 15
                        },
                        new
                        {
                            IngredientsId = 52,
                            ReviewId = 15
                        },
                        new
                        {
                            IngredientsId = 53,
                            ReviewId = 16
                        },
                        new
                        {
                            IngredientsId = 17,
                            ReviewId = 16
                        },
                        new
                        {
                            IngredientsId = 1,
                            ReviewId = 16
                        },
                        new
                        {
                            IngredientsId = 6,
                            ReviewId = 16
                        });
                });

            modelBuilder.Entity("Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("Picture");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ReviewId = 3,
                            Url = "https://pub-06851190cddc4684902b556426d2e9a1.r2.dev/IMG_4685.jpg"
                        });
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeoLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTimeOffset(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "I added an egg and bacon. bacon wasn’t crispy. egg wasn’t over easy which is a shame. \n            probably 4 stars worthy at the restaurant. \n            https://www.facebook.com/burgerboss.br",
                            GeoLocation = "n/a",
                            Insta = "n/a",
                            Location = "Burger Boss",
                            Name = "Burger Boss",
                            Price = 8m,
                            Rating = 3.5m
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTimeOffset(new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "bun toasted sesame seed. bacon was cooked perfectly.\n            ordered medium - was more medium well. overall very good burger. probably better as a single.\n            maybe slightly less mayo but it was a very good burger special butter mayo.",
                            GeoLocation = "n/a",
                            Insta = "n/a",
                            Location = "Burgers and Beyond  (Shoreditch London)",
                            Name = "Butter Burger (double)",
                            Price = 0m,
                            Rating = 5m
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTimeOffset(new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "First bite impression: very large and messy. some of the meat fell out when i bit into it.\n            The meat was very crumbly and other took all the flavor. It wasn't falvored very well either. A little dissapointing.\n            It looked incredible as you'll see from the picture.",
                            GeoLocation = "n/a",
                            Insta = "https://www.instagram.com/spitalfieldse1/",
                            Location = "The Grime Burger (Shoreditch London)",
                            Name = "Double Grime Burger",
                            Price = 0m,
                            Rating = 3.5m
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTimeOffset(new DateTime(2024, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "a bit on the small side. messy to eat. solid but not amazing. i’ve been here before and only realized after i was on the way. the place is located in what feels like a neighborhood lol. \n            Can’t put my finger on what i’d improve but it does leave you wanting a bit more. maybe it’s the size. smash patties were cooked medium rare and it was juicy. \n            maybe i’m being hard on it because the burger from burgers and beyond is better and they’re very close to each other location wise. order the green chile fries to match. \n            was less impressed by that.  the nacho cheese was a bit much. but they were tasty.\n             think the price during lunch is reasonable so i give it a little bum because of that.\n             address: 15 Hoxton Market, London N1 6HG, United Kingdom",
                            GeoLocation = "n/a",
                            Insta = "",
                            Location = "MEATliqour",
                            Name = "Green Chili Double",
                            Price = 0m,
                            Rating = 4.5m
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTimeOffset(new DateTime(2024, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "solid burger. fresh ingredients. i forgot to add an egg. meat was pretty dry.\n             very spicy which i like. didn’t have any woah factor. \n            for the ingredients listed i expected more.\n             the bad boy sauce i think over powered the favor.",
                            GeoLocation = "n/a",
                            Insta = "",
                            Location = "Smokey Boys",
                            Name = "Smokey Bad Boy",
                            Price = 16.77m,
                            Rating = 3.5m
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTimeOffset(new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "egg was over cooked. tons of pickles. \n            perfect brioche bun. meat was exceptional. probably sauced",
                            GeoLocation = "n/a",
                            Insta = "",
                            Location = "LA Central Burger",
                            Name = "Double smash (Black Angus)",
                            Price = 0m,
                            Rating = 4.5m
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTimeOffset(new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "I would have to say almost perfect. i don’t feel like i can give a perfect rating but this is damn near close. \n            meat was cooked perfectly (medium rare). added an egg which was also cooked prefect. \n            bacon wasn’t crispy but that could be due to the chili. japenqos were sweet than spicy.\n             overall i’m very impressed. only criticism is that when i cut it.\n             the second half didn’t have as much meat. could of been a poor knife job on my part",
                            GeoLocation = "n/a",
                            Insta = "",
                            Location = "Ground Burger (Lisbon)",
                            Name = "Chili Con Carne",
                            Price = 32.96m,
                            Rating = 5m
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTimeOffset(new DateTime(2024, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "having a hard time rating this. since the chili burger was amazing. this was extremely disappointing.\n             meat was cooked well done. and since it was 70% of the burger it didn’t really help the situation.\n              egg was also over cooked. i went during lunch time so maybe the crowd reduced the quality.\n            also come to the conclusion i don’t like doubles unless they’re smash patty’s.\n             just too much meat to bun for it to be enjoyable otherwise.\n             also 24 euros is a bit of a buzz kill",
                            GeoLocation = "n/a",
                            Insta = "",
                            Location = "Ground Burger (Time Out Market: Lisbon)",
                            Name = "Double Cheese",
                            Price = 26m,
                            Rating = 4m
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTimeOffset(new DateTime(2024, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "I added bacon. first bite i had a very fresh taste in my mouth.\n             normally don’t do lettuce but it was nice on this burger.\n              hot is definitely not proper heat. mild at best.\n               very solid. meat was cooked medium/medium rare without requesting it.\n             got sweet potato chips. they’re what you’d expect. price 15 euros",
                            GeoLocation = "n/a",
                            Insta = "",
                            Location = "To.b (Lisbon)",
                            Name = "Hot",
                            Price = 16.5m,
                            Rating = 4.5m
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTimeOffset(new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "I knew it wouldn’t be good, still managed even failed to meet my low expectations.\n             meat was dry and chewy. i didn’t even bother to eat the bun. it was an egg bun i think. very dense.\n             funny enough the ketchup made it more editable. american cheese, ketchup, raw white onions",
                            GeoLocation = "n/a",
                            Insta = "",
                            Location = "Nathan’s (Miami Airport)",
                            Name = "Double Cheese",
                            Price = 0m,
                            Rating = 1m
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTimeOffset(new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "First impression: Saucy not in a good best way. \n            The sauce caused the bun to become soggy and it didn't hold up well when biting. \n            Next time get the sauce and manasise on the side. Meat was well cooked,\n            Ingredients: Dry Aged Beef Patties, Cold Smoked American Cheese, Steak Sauce 2.0, Marrownaise, Beef Fat Onions",
                            GeoLocation = "n/a",
                            Insta = "",
                            Location = "Burgers and Beyond (Shoreditch London)",
                            Name = "The Bougie Burher",
                            Price = 0m,
                            Rating = 5m
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTimeOffset(new DateTime(2024, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "crispy with an explosion of sayory favor. Only thing is I wish it was bigger.\n             Luckily i ordered another one",
                            GeoLocation = "n/a",
                            Insta = "",
                            Location = "Honest Burger (London)",
                            Name = "Smashed By Honest",
                            Price = 0m,
                            Rating = 5m
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTimeOffset(new DateTime(2024, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "First bite: tasted fresh. On the smaller side of things",
                            GeoLocation = "n/a",
                            Insta = "",
                            Location = "Honest Burger (London)",
                            Name = "Chili Burger",
                            Price = 0m,
                            Rating = 5m
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTimeOffset(new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "First bite: exactly what you'd expect from a smashed burger. \n            I always added bacon, japs, mushrooms and oions. Tasted very fresh. I was satisfied by the end of it.\n             only small issue is it wasn't that hot. it was midnight so i assume that had a little to do with it.",
                            GeoLocation = "n/a",
                            Insta = "",
                            Location = "Five guys (London)",
                            Name = "Double Cheese",
                            Price = 0m,
                            Rating = 4m
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTimeOffset(new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "One of my favorite chain restuarant burger. Brings back memories of having them with my mom in florida.\n            Very good burger. Right amount of spice. Meat was cooked prefect for medium rare.",
                            GeoLocation = "n/a",
                            Insta = "",
                            Location = "Bj's (Rancho Cucamonga)",
                            Name = "Crispy Jalapeno Burger",
                            Price = 0m,
                            Rating = 5m
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTimeOffset(new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "meat was cooked perfectly for medium rare. seasoned well. maybe a bit too much lettuce but it was fresh and added a nice crispy crunch. \n            bun covered the burger perfectly. i was able to eat it without it falling apart. bacon was cooked well. had a little crunch to it. \n            ingredients: ground rib eye patty*, mozzarella cheese, bacon, lettuce\n            included potato wedges. Address: Blvd. Paseo de la Marina S/N, Centro, 23450 Cabo San Lucas, B.C.S., Mexico",
                            GeoLocation = "n/a",
                            Insta = "https://www.instagram.com/outpostcabo?igsh=cjc3eDhkNHl2N29h",
                            Location = "Outpost (Cabo San Lucas)",
                            Name = "Op Burger",
                            Price = 17.5m,
                            Rating = 5m
                        });
                });

            modelBuilder.Entity("IngredientReview", b =>
                {
                    b.HasOne("Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Review", null)
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Picture", b =>
                {
                    b.HasOne("Review", null)
                        .WithMany("Pics")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.Navigation("Pics");
                });
#pragma warning restore 612, 618
        }
    }
}
